#!/bin/bash
lsb_var=$(lsb_release -c)
os_code=${lsb_var:10}

if [ "$1" != "" ]; then
    if [ "$1" == "clean" ]; then
      if [ -d "debian" ]; then
      echo "Clearing rules."
      rm -rf debian
      rm -rf obj-x86_64-linux-gnu
      fi
    fi
    if [ "$1" == "do" ]; then
      bloom-generate rosdebian --os-name ubuntu --os-version $os_code --ros-distro $ROS_DISTRO
      fakeroot debian/rules binary
    fi
else
  if [ -d "debian" ]; then
  echo "Clearing rules."
  rm -rf debian
  rm -rf obj-x86_64-linux-gnu
  fi
  echo "Generating rules."
  bloom-generate rosdebian --os-name ubuntu --os-version $os_code --ros-distro $ROS_DISTRO
  fakeroot debian/rules binary
  echo "Done."
fi
